language: objective-c

env:
  global:
    - EnableNuGetPackageRestore=true
  matrix:
    - MONO_VERSION="3.10.0"

install:
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  - mono .nuget/NuGet.exe install NUnit.Runners -Version 2.6.3 -OutputDirectory tools

script: 
  - xbuild /property:Configuration="Release (net40)" ExtCore.sln
  - xbuild /property:Configuration="Release (net45)" ExtCore.sln
  - xbuild /property:Configuration="Release (profile47)" ExtCore.sln
  - mono --runtime=v4.0.30319 ./tools/NUnit.Runners.2.6.3/tools/nunit-console.exe ./ExtCore.Tests/bin/net40/Release/ExtCore.Tests.dll
  - mono --runtime=v4.0.30319 ./tools/NUnit.Runners.2.6.3/tools/nunit-console.exe ./ExtCore.Tests/bin/net45/Release/ExtCore.Tests.dll
  - mono --runtime=v4.0.30319 ./tools/NUnit.Runners.2.6.3/tools/nunit-console.exe ./ExtCore.Tests/bin/profile47/Release/ExtCore.Tests.dll
