language: objective-c

env:
  matrix:
    - MONO_VERSION="3.2.5"

before_install:
  - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script: "xbuild /property:Configuration=Release ExtCore.sln && mono ./packages/NUnit.Runners.2.6.1/tools/nunit-console.exe ./ExtCore.Tests/bin/Release/ExtCore.Tests.dll"

