language: csharp

# Use container-based infrastructure with Ubuntu Trusty (14.04)
dist: trusty
sudo: false

# TODO : Enable both mono and dotnet builds: https://docs.travis-ci.com/user/languages/csharp/#Testing-Against-Mono-and-.NET-Core
mono:
  - latest

env:
  global:
    - EnableNuGetPackageRestore=true

install:
  - nuget restore ExtCore.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory tools

# TODO : Add before_script section to clone fsharp/fsharp repo and compile it, so fsc-proto can be used.
#        Cache the compiled fsharp build (using travis CI caching functionality) so it doesn't have to run every time.
# TODO : Use build matrix to run two jobs; one where we build/test via the solution, and another where we build through proto-compile
#        https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-Including-Jobs

script:
  - xbuild /property:Configuration="Release (net40)" ExtCore.sln
  - xbuild /property:Configuration="Release (net45)" ExtCore.sln
#  - xbuild /property:Configuration="Release (profile7)" ExtCore.sln
#  - xbuild /property:Configuration="Release (profile47)" ExtCore.sln
#  - xbuild /property:Configuration="Release (profile78)" ExtCore.sln
#  - xbuild /property:Configuration="Release (profile259)" ExtCore.sln
  - mono --runtime=v4.0.30319 ./tools/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExtCore.Tests/bin/net40/Release/ExtCore.Tests.dll
  - mono --runtime=v4.0.30319 ./tools/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExtCore.Tests/bin/net45/Release/ExtCore.Tests.dll
#  - mono --runtime=v4.0.30319 ./tools/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExtCore.Tests/bin/profile7/Release/ExtCore.Tests.dll
#  - mono --runtime=v4.0.30319 ./tools/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExtCore.Tests/bin/profile47/Release/ExtCore.Tests.dll
#  - mono --runtime=v4.0.30319 ./tools/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExtCore.Tests/bin/profile78/Release/ExtCore.Tests.dll
#  - mono --runtime=v4.0.30319 ./tools/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExtCore.Tests/bin/profile259/Release/ExtCore.Tests.dll
